"""Create Users

Revision ID: 574057767f63
Revises: c24a2ea024b5
Create Date: 2024-05-24 11:42:47.284546

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '574057767f63'
down_revision = 'c24a2ea024b5'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('email', sa.String(), nullable=True),
    sa.Column('password', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('users')
    # ### end Alembic commands ###
