"""Create Database Tables

Revision ID: fec379c49add
Revises: 
Create Date: 2024-05-29 09:56:30.742930

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'fec379c49add'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('course',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_course'))
    )
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('email', sa.String(), nullable=True),
    sa.Column('password', sa.String(), nullable=True),
    sa.Column('role', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_users'))
    )
    op.create_table('student',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('first_name', sa.String(), nullable=True),
    sa.Column('last_name', sa.String(), nullable=True),
    sa.Column('email', sa.String(), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_student_user_id_users')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_student'))
    )
    op.create_table('biodata',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('hometown', sa.String(), nullable=True),
    sa.Column('contact', sa.String(), nullable=True),
    sa.Column('student_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['student_id'], ['student.id'], name=op.f('fk_biodata_student_id_student')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_biodata'))
    )
    op.create_table('student_course',
    sa.Column('course_id', sa.Integer(), nullable=True),
    sa.Column('student_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['course_id'], ['course.id'], name=op.f('fk_student_course_course_id_course')),
    sa.ForeignKeyConstraint(['student_id'], ['student.id'], name=op.f('fk_student_course_student_id_student'))
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('student_course')
    op.drop_table('biodata')
    op.drop_table('student')
    op.drop_table('users')
    op.drop_table('course')
    # ### end Alembic commands ###
